# linkhou/launch/spawn_controllers.launch.py
"""
Custom spawn_controllers with delay for trajectory controller.
Replaces the default one generated by moveit_configs_utils.
"""

from launch import LaunchDescription
from launch.actions import TimerAction, DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    # 延迟时间参数（秒）
    declared_arguments = [
        DeclareLaunchArgument(
            "trajectory_controller_start_delay",
            default_value="30.0",
            description="Seconds to wait before spawning the trajectory controller.",
        )
    ]

    delay = LaunchConfiguration("trajectory_controller_start_delay")

    # joint_state_broadcaster: 安全，可以立即启动
    joint_state_broadcaster_spawner = Node(
        package="controller_manager",
        executable="spawner",
        arguments=["joint_state_broadcaster", "--controller-manager", "/controller_manager"],
        output="screen",
    )

    # arm_controller: 轨迹控制器，必须延迟启动！
    arm_controller_spawner = Node(
        package="controller_manager",
        executable="spawner",
        arguments=["arm_controller", "--controller-manager", "/controller_manager"],
        output="screen",
    )

    return LaunchDescription([
        *declared_arguments,

        # 立即启动 joint_state_broadcaster
        joint_state_broadcaster_spawner,

        # 延迟启动 arm_controller
        TimerAction(
            period=delay,
            actions=[arm_controller_spawner],
        ),
    ])

# # spawn_controllers.launch.py
# from launch import LaunchDescription
# from launch.actions import TimerAction, OpaqueFunction
# from launch_ros.actions import Node
# import os
# from ament_index_python.packages import get_package_share_directory


# def get_delayed_controller_spawners(context):
#     """
#     动态获取 moveit_config 并构建安全的控制器启动逻辑
#     注意：这里不能直接传 moveit_config，所以通过环境变量或硬编码处理
#     """
#     # 方案一：假设你知道包结构，手动构造 moveit_config（适用于固定机器人）
#     pkg_name = "linkhou"
#     pkg_share = get_package_share_directory(pkg_name)

#     # 加载 moveit_controllers.yaml
#     from moveit_configs_utils import MoveItConfigsBuilder
#     moveit_config = MoveItConfigsBuilder("LR4_R560", pkg_name).to_moveit_configs()

#     # 提取 controller_names（来自 moveit_simple_controller_manager）
#     controller_names = moveit_config.trajectory_execution.get(
#         "moveit_simple_controller_manager", {}
#     ).get("controller_names", [])

#     nodes = []

#     # 1. 立即启动 joint_state_broadcaster
#     nodes.append(
#         Node(
#             package="controller_manager",
#             executable="spawner",
#             arguments=["joint_state_broadcaster", "--controller-manager", "/controller_manager"],
#             output="screen",
#         )
#     )

#     # 2. 延迟启动所有 trajectory 控制器
#     delayed_actions = []
#     for controller in controller_names:
#         delayed_actions.append(
#             Node(
#                 package="controller_manager",
#                 executable="spawner",
#                 arguments=[controller, "--controller-manager", "/controller_manager"],
#                 output="screen",
#             )
#         )

#     # 使用 TimerAction 延迟启动所有 trajectory 控制器
#     nodes.append(
#         TimerAction(
#             period=8.0,  # 可以改为 DeclareLaunchArgument 参数
#             actions=delayed_actions,
#         )
#     )

#     return nodes


# def generate_launch_description():
#     return LaunchDescription([
#         OpaqueFunction(function=get_delayed_controller_spawners)
#     ])
